version: '3.3'
services:
  # NGINX Plus Load Balancer
  nginx-plus:
      container_name: nginx-plus
      hostname: nginx-plus
      build: nginx-plus
      volumes:
          - ./nginx-plus/etc/nginx:/etc/nginx
      ports:
          - 8080:8080
          - 80:80
          - 443:443
          - 9000:9000
      restart: always
      networks:
          - kind
  # debug-ubuntu:
  #   container_name: debug-ubuntu
  #   hostname: debug-ubuntu
  #   image: ubuntu:23.10
  #   stdin_open: true # docker run -i
  #   tty: true        # docker run -t
  #   restart: always
  #   networks:
  #       - kind
  prometheus:
    container_name: prometheus-external
    hostname: prometheus-external
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - kind

  grafana:
    container_name: grafana-external
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - kind

volumes:
  grafana-storage:

networks:
  kind:
    name: kind
    driver: bridge
    external: true
