apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  annotations:
    nginxinc.io/nlk-cafe: "http"   # Must be added
spec:
  type: LoadBalancer
  externalIPs:
  - PLUS_IP 
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: nlk-cafe     # Must match Nginx upstream name
  selector:
    app: nginx-ingress
